### ISSUE TITLE
Error on install: no such file or directory sites/undefined/config.yml

### ISSUE THREAD

**Issue by dafeder** [interra/data-generate#1]
## Issue Type

- [x] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md#feature-requests)

## Description

During `npm install` I get the following output right before it outputs the dependency tree:

```
Building the Webpack DLL...
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/dfeder/Sites/data-generate/sites/undefined/config.yml'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.<anonymous> (/home/dfeder/Sites/data-generate/internals/webpack/webpack.base.babel.js:18:19)
    at Module._compile (module.js:570:32)
    at loader (/home/dfeder/Sites/data-generate/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/dfeder/Sites/data-generate/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

## Steps to reproduce

* Clone repo (at `01f2f9d` at time of report)
* Run `npm install`
* Cry 

# Versions

- React-Boilerplate (see `package.json`): (not found?)
- Node/NPM: 3.10.10
- Browser: n/a

**Comment by acouch** [comment]
I've removed that file. Tests including npm install now passing: https://travis-ci.org/interra/data-generate/jobs/296265729#L426
